name: pvpWorld
version: '1.0-SNAPSHOT'
main: mark.tofu.pvpworld.PvpWorld
api-version: '1.16'
commands:
  pvpworld:
    description: sendMessage about this world
  pvpworld help:
    description: sendMessage about help
  pvpworld command:
    description: sendMessage all comamnds
  pvpworld notice:
    description: sendMessage notifications