name: pvpWorld
version: '1.0-SNAPSHOT'
main: mark.tofu.pvpworld.PvpWorld
api-version: '1.16'
commands:
  pvpworld:
    description: sendMessage about this world
  pvpworld op bm true:
    description: player into build mode
  pvpworld op bm false:
    description: player into normal mode
  pvpworld op gm c:
    description: player gamemode set to creative
  pvpworld op gm s:
    description: player gamemode set to survival